# This is a basic workflow to help you get started with Actions

name: Deploy to Live Channel

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy_live_website:
    env:
      CI: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - run: yarn install && yarn build
        working-directory: front-end
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_UTDECSEVENTS }}"
          projectId: utdecsevents-9bed0
          channelId: live
          entryPoint: "./front-end"
